/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Delma
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnIncio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        MnArchivo = new javax.swing.JMenu();
        MnSalir = new javax.swing.JMenuItem();
        MnMantenimiento = new javax.swing.JMenu();
        MnAlumno = new javax.swing.JMenuItem();
        MnCurso = new javax.swing.JMenuItem();
        MnRegistro = new javax.swing.JMenu();
        MnMatricula = new javax.swing.JMenuItem();
        MnRetiro = new javax.swing.JMenuItem();
        MnConsulta = new javax.swing.JMenu();
        MnConAlumno = new javax.swing.JMenuItem();
        MnConCurso = new javax.swing.JMenuItem();
        MnConMatricula = new javax.swing.JMenuItem();
        MnConRetiro = new javax.swing.JMenuItem();
        MnReporte = new javax.swing.JMenu();
        MnAlumPen = new javax.swing.JMenuItem();
        MnAlumVigen = new javax.swing.JMenuItem();
        MnAlumCur = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        pnIncio.setPreferredSize(new java.awt.Dimension(800, 475));

        javax.swing.GroupLayout pnIncioLayout = new javax.swing.GroupLayout(pnIncio);
        pnIncio.setLayout(pnIncioLayout);
        pnIncioLayout.setHorizontalGroup(
            pnIncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 989, Short.MAX_VALUE)
        );
        pnIncioLayout.setVerticalGroup(
            pnIncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        MnArchivo.setText("Archivo");

        MnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnSalir.setText("Salir");
        MnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnSalirActionPerformed(evt);
            }
        });
        MnArchivo.add(MnSalir);

        jMenuBar2.add(MnArchivo);

        MnMantenimiento.setText("Mantenimiento");

        MnAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        MnAlumno.setText("Alumno");
        MnAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAlumnoActionPerformed(evt);
            }
        });
        MnMantenimiento.add(MnAlumno);

        MnCurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        MnCurso.setText("Curso");
        MnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCursoActionPerformed(evt);
            }
        });
        MnMantenimiento.add(MnCurso);

        jMenuBar2.add(MnMantenimiento);

        MnRegistro.setText("Registro");

        MnMatricula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        MnMatricula.setText("Matricula");
        MnMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnMatriculaActionPerformed(evt);
            }
        });
        MnRegistro.add(MnMatricula);

        MnRetiro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        MnRetiro.setText("Retiro");
        MnRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRetiroActionPerformed(evt);
            }
        });
        MnRegistro.add(MnRetiro);

        jMenuBar2.add(MnRegistro);

        MnConsulta.setText("Consulta");

        MnConAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnConAlumno.setText("Alumno");
        MnConAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnConAlumnoActionPerformed(evt);
            }
        });
        MnConsulta.add(MnConAlumno);

        MnConCurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnConCurso.setText("Curso");
        MnConCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnConCursoActionPerformed(evt);
            }
        });
        MnConsulta.add(MnConCurso);

        MnConMatricula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnConMatricula.setText("Matricula");
        MnConMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnConMatriculaActionPerformed(evt);
            }
        });
        MnConsulta.add(MnConMatricula);

        MnConRetiro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnConRetiro.setText("Retiro");
        MnConRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnConRetiroActionPerformed(evt);
            }
        });
        MnConsulta.add(MnConRetiro);

        jMenuBar2.add(MnConsulta);

        MnReporte.setText("Reporte");

        MnAlumPen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        MnAlumPen.setText("Alumno con matricula pendiente");
        MnAlumPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAlumPenActionPerformed(evt);
            }
        });
        MnReporte.add(MnAlumPen);

        MnAlumVigen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        MnAlumVigen.setText("Alumno con matricula vigente");
        MnAlumVigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAlumVigenActionPerformed(evt);
            }
        });
        MnReporte.add(MnAlumVigen);

        MnAlumCur.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        MnAlumCur.setText("Alumnos matriculados por curso");
        MnAlumCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAlumCurActionPerformed(evt);
            }
        });
        MnReporte.add(MnAlumCur);

        jMenuBar2.add(MnReporte);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnIncio, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnIncio, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MnSalirActionPerformed

    private void MnAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAlumnoActionPerformed
        
        frmAlumno ventana= new frmAlumno();
        pnIncio.add(ventana);
        ventana.show();
        
    }//GEN-LAST:event_MnAlumnoActionPerformed

    private void MnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCursoActionPerformed
        frmCurso ventana = new frmCurso();
         pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnCursoActionPerformed

    private void MnMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnMatriculaActionPerformed
        frmMatricula ventana = new frmMatricula();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnMatriculaActionPerformed

    private void MnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRetiroActionPerformed
        frmRetiro ventana = new frmRetiro();
         pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnRetiroActionPerformed

    private void MnConAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnConAlumnoActionPerformed
        frmConAlumno ventana = new frmConAlumno();
         pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnConAlumnoActionPerformed

    private void MnConCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnConCursoActionPerformed
        frmConCurso ventana = new frmConCurso();
         pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnConCursoActionPerformed

    private void MnConMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnConMatriculaActionPerformed
        frmConMatricula ventana = new frmConMatricula();
         pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnConMatriculaActionPerformed

    private void MnConRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnConRetiroActionPerformed
        frmConRetiro ventana = new frmConRetiro();
         pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnConRetiroActionPerformed

    private void MnAlumPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAlumPenActionPerformed
        // TODO add your handling code here:
        frmReportePendiente ventana = new frmReportePendiente();
         pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnAlumPenActionPerformed

    private void MnAlumVigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAlumVigenActionPerformed
        // TODO add your handling code here:
        frmMatriculaVigente ventana = new frmMatriculaVigente();
         pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnAlumVigenActionPerformed

    private void MnAlumCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAlumCurActionPerformed
        // TODO add your handling code here:
        frmMatriculadosCurso ventana = new frmMatriculadosCurso();
         pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnAlumCurActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnAlumCur;
    private javax.swing.JMenuItem MnAlumPen;
    private javax.swing.JMenuItem MnAlumVigen;
    private javax.swing.JMenuItem MnAlumno;
    private javax.swing.JMenu MnArchivo;
    private javax.swing.JMenuItem MnConAlumno;
    private javax.swing.JMenuItem MnConCurso;
    private javax.swing.JMenuItem MnConMatricula;
    private javax.swing.JMenuItem MnConRetiro;
    private javax.swing.JMenu MnConsulta;
    private javax.swing.JMenuItem MnCurso;
    private javax.swing.JMenu MnMantenimiento;
    private javax.swing.JMenuItem MnMatricula;
    private javax.swing.JMenu MnRegistro;
    private javax.swing.JMenu MnReporte;
    private javax.swing.JMenuItem MnRetiro;
    private javax.swing.JMenuItem MnSalir;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JDesktopPane pnIncio;
    // End of variables declaration//GEN-END:variables
}
